{
 "title": "ArangoDB- SYDNEY",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Availability",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "arangodb_up", "legendFormat": "arangodb_server_uptime" }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_last_leader_tick - arangodb_last_follower_tick",
     "legendFormat": "Lag between leader and follower"
    }
   ]
  },
  {
   "title": "Server ROLE",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "arangodb_is_leader", "legendFormat": "arangodb_server_uptime" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "arangodb_server_uptime", "legendFormat": "arangodb_server_uptime" }
   ]
  },
  {
   "title": "Threads in-progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "arangodb_server_threads_in_progress",
     "legendFormat": "arangodb_server_threads_in_progress"
    }
   ]
  },
  {
   "title": "Server threads queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "arangodb_server_threads_queued", "legendFormat": "arangodb_server_threads_queued" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~'arango3.*'}) by (pod_name)"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=~\"arango3.*\"}",
     "legendFormat": "Resource Limit"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "arangodb_clientConnectionsCurrent",
     "legendFormat": "Active Client Connections"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(arangodb_http_requestsTotal[2m])",
     "legendFormat": "arangodb_http_requestsTotal"
    }
   ]
  }
 ]
}